//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdapterProjekt.WebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceReference.InterfaceSoap")]
    public interface InterfaceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AdapterProjekt.WebServiceReference.HelloWorldResponse HelloWorld(AdapterProjekt.WebServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AdapterProjekt.WebServiceReference.HelloWorldResponse> HelloWorldAsync(AdapterProjekt.WebServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name HelloMikeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloMike", ReplyAction="*")]
        AdapterProjekt.WebServiceReference.HelloMikeResponse HelloMike(AdapterProjekt.WebServiceReference.HelloMikeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloMike", ReplyAction="*")]
        System.Threading.Tasks.Task<AdapterProjekt.WebServiceReference.HelloMikeResponse> HelloMikeAsync(AdapterProjekt.WebServiceReference.HelloMikeRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLog", ReplyAction="*")]
        AdapterProjekt.WebServiceReference.AddLogResponse AddLog(AdapterProjekt.WebServiceReference.AddLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLog", ReplyAction="*")]
        System.Threading.Tasks.Task<AdapterProjekt.WebServiceReference.AddLogResponse> AddLogAsync(AdapterProjekt.WebServiceReference.AddLogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AdapterProjekt.WebServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AdapterProjekt.WebServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdapterProjekt.WebServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AdapterProjekt.WebServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloMikeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloMike", Namespace="http://tempuri.org/", Order=0)]
        public AdapterProjekt.WebServiceReference.HelloMikeRequestBody Body;
        
        public HelloMikeRequest() {
        }
        
        public HelloMikeRequest(AdapterProjekt.WebServiceReference.HelloMikeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloMikeRequestBody {
        
        public HelloMikeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloMikeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloMikeResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdapterProjekt.WebServiceReference.HelloMikeResponseBody Body;
        
        public HelloMikeResponse() {
        }
        
        public HelloMikeResponse(AdapterProjekt.WebServiceReference.HelloMikeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloMikeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloMikeResult;
        
        public HelloMikeResponseBody() {
        }
        
        public HelloMikeResponseBody(string HelloMikeResult) {
            this.HelloMikeResult = HelloMikeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLog", Namespace="http://tempuri.org/", Order=0)]
        public AdapterProjekt.WebServiceReference.AddLogRequestBody Body;
        
        public AddLogRequest() {
        }
        
        public AddLogRequest(AdapterProjekt.WebServiceReference.AddLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string action;
        
        public AddLogRequestBody() {
        }
        
        public AddLogRequestBody(string ID, System.DateTime timestamp, string action) {
            this.ID = ID;
            this.timestamp = timestamp;
            this.action = action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdapterProjekt.WebServiceReference.AddLogResponseBody Body;
        
        public AddLogResponse() {
        }
        
        public AddLogResponse(AdapterProjekt.WebServiceReference.AddLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddLogResult;
        
        public AddLogResponseBody() {
        }
        
        public AddLogResponseBody(string AddLogResult) {
            this.AddLogResult = AddLogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfaceSoapChannel : AdapterProjekt.WebServiceReference.InterfaceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceSoapClient : System.ServiceModel.ClientBase<AdapterProjekt.WebServiceReference.InterfaceSoap>, AdapterProjekt.WebServiceReference.InterfaceSoap {
        
        public InterfaceSoapClient() {
        }
        
        public InterfaceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdapterProjekt.WebServiceReference.HelloWorldResponse AdapterProjekt.WebServiceReference.InterfaceSoap.HelloWorld(AdapterProjekt.WebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AdapterProjekt.WebServiceReference.HelloWorldRequest inValue = new AdapterProjekt.WebServiceReference.HelloWorldRequest();
            inValue.Body = new AdapterProjekt.WebServiceReference.HelloWorldRequestBody();
            AdapterProjekt.WebServiceReference.HelloWorldResponse retVal = ((AdapterProjekt.WebServiceReference.InterfaceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdapterProjekt.WebServiceReference.HelloWorldResponse> AdapterProjekt.WebServiceReference.InterfaceSoap.HelloWorldAsync(AdapterProjekt.WebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdapterProjekt.WebServiceReference.HelloWorldResponse> HelloWorldAsync() {
            AdapterProjekt.WebServiceReference.HelloWorldRequest inValue = new AdapterProjekt.WebServiceReference.HelloWorldRequest();
            inValue.Body = new AdapterProjekt.WebServiceReference.HelloWorldRequestBody();
            return ((AdapterProjekt.WebServiceReference.InterfaceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdapterProjekt.WebServiceReference.HelloMikeResponse AdapterProjekt.WebServiceReference.InterfaceSoap.HelloMike(AdapterProjekt.WebServiceReference.HelloMikeRequest request) {
            return base.Channel.HelloMike(request);
        }
        
        public string HelloMike() {
            AdapterProjekt.WebServiceReference.HelloMikeRequest inValue = new AdapterProjekt.WebServiceReference.HelloMikeRequest();
            inValue.Body = new AdapterProjekt.WebServiceReference.HelloMikeRequestBody();
            AdapterProjekt.WebServiceReference.HelloMikeResponse retVal = ((AdapterProjekt.WebServiceReference.InterfaceSoap)(this)).HelloMike(inValue);
            return retVal.Body.HelloMikeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdapterProjekt.WebServiceReference.HelloMikeResponse> AdapterProjekt.WebServiceReference.InterfaceSoap.HelloMikeAsync(AdapterProjekt.WebServiceReference.HelloMikeRequest request) {
            return base.Channel.HelloMikeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdapterProjekt.WebServiceReference.HelloMikeResponse> HelloMikeAsync() {
            AdapterProjekt.WebServiceReference.HelloMikeRequest inValue = new AdapterProjekt.WebServiceReference.HelloMikeRequest();
            inValue.Body = new AdapterProjekt.WebServiceReference.HelloMikeRequestBody();
            return ((AdapterProjekt.WebServiceReference.InterfaceSoap)(this)).HelloMikeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdapterProjekt.WebServiceReference.AddLogResponse AdapterProjekt.WebServiceReference.InterfaceSoap.AddLog(AdapterProjekt.WebServiceReference.AddLogRequest request) {
            return base.Channel.AddLog(request);
        }
        
        public string AddLog(string ID, System.DateTime timestamp, string action) {
            AdapterProjekt.WebServiceReference.AddLogRequest inValue = new AdapterProjekt.WebServiceReference.AddLogRequest();
            inValue.Body = new AdapterProjekt.WebServiceReference.AddLogRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.timestamp = timestamp;
            inValue.Body.action = action;
            AdapterProjekt.WebServiceReference.AddLogResponse retVal = ((AdapterProjekt.WebServiceReference.InterfaceSoap)(this)).AddLog(inValue);
            return retVal.Body.AddLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdapterProjekt.WebServiceReference.AddLogResponse> AdapterProjekt.WebServiceReference.InterfaceSoap.AddLogAsync(AdapterProjekt.WebServiceReference.AddLogRequest request) {
            return base.Channel.AddLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdapterProjekt.WebServiceReference.AddLogResponse> AddLogAsync(string ID, System.DateTime timestamp, string action) {
            AdapterProjekt.WebServiceReference.AddLogRequest inValue = new AdapterProjekt.WebServiceReference.AddLogRequest();
            inValue.Body = new AdapterProjekt.WebServiceReference.AddLogRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.timestamp = timestamp;
            inValue.Body.action = action;
            return ((AdapterProjekt.WebServiceReference.InterfaceSoap)(this)).AddLogAsync(inValue);
        }
    }
}
