//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebsite.WebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://grandt.us:90/WebService/", ConfigurationName="WebServiceReference.InterfaceSoap")]
    public interface InterfaceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/HelloAdd", ReplyAction="*")]
        int HelloAdd(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/HelloAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<int> HelloAddAsync(int a, int b);
        
        // CODEGEN: Generating message contract since element name TestMethodResult from namespace http://grandt.us:90/WebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/TestMethod", ReplyAction="*")]
        MainWebsite.WebServiceReference.TestMethodResponse TestMethod(MainWebsite.WebServiceReference.TestMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/TestMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.TestMethodResponse> TestMethodAsync(MainWebsite.WebServiceReference.TestMethodRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://grandt.us:90/WebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/HelloWorld", ReplyAction="*")]
        MainWebsite.WebServiceReference.HelloWorldResponse HelloWorld(MainWebsite.WebServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.HelloWorldResponse> HelloWorldAsync(MainWebsite.WebServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://grandt.us:90/WebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/Login", ReplyAction="*")]
        MainWebsite.WebServiceReference.LoginResponse Login(MainWebsite.WebServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.LoginResponse> LoginAsync(MainWebsite.WebServiceReference.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://grandt.us:90/WebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddUser", ReplyAction="*")]
        MainWebsite.WebServiceReference.AddUserResponse AddUser(MainWebsite.WebServiceReference.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddUserResponse> AddUserAsync(MainWebsite.WebServiceReference.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://grandt.us:90/WebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddEventForType", ReplyAction="*")]
        MainWebsite.WebServiceReference.AddEventForTypeResponse AddEventForType(MainWebsite.WebServiceReference.AddEventForTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddEventForType", ReplyAction="*")]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddEventForTypeResponse> AddEventForTypeAsync(MainWebsite.WebServiceReference.AddEventForTypeRequest request);
        
        // CODEGEN: Generating message contract since element name customer from namespace http://grandt.us:90/WebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddCustomer", ReplyAction="*")]
        MainWebsite.WebServiceReference.AddCustomerResponse AddCustomer(MainWebsite.WebServiceReference.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddCustomerResponse> AddCustomerAsync(MainWebsite.WebServiceReference.AddCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://grandt.us:90/WebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddLog", ReplyAction="*")]
        MainWebsite.WebServiceReference.AddLogResponse AddLog(MainWebsite.WebServiceReference.AddLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddLog", ReplyAction="*")]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddLogResponse> AddLogAsync(MainWebsite.WebServiceReference.AddLogRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://grandt.us:90/WebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddType", ReplyAction="*")]
        MainWebsite.WebServiceReference.AddTypeResponse AddType(MainWebsite.WebServiceReference.AddTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddType", ReplyAction="*")]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddTypeResponse> AddTypeAsync(MainWebsite.WebServiceReference.AddTypeRequest request);
        
        // CODEGEN: Generating message contract since element name UnitID from namespace http://grandt.us:90/WebService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddUnit", ReplyAction="*")]
        MainWebsite.WebServiceReference.AddUnitResponse AddUnit(MainWebsite.WebServiceReference.AddUnitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grandt.us:90/WebService/AddUnit", ReplyAction="*")]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddUnitResponse> AddUnitAsync(MainWebsite.WebServiceReference.AddUnitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMethod", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.TestMethodRequestBody Body;
        
        public TestMethodRequest() {
        }
        
        public TestMethodRequest(MainWebsite.WebServiceReference.TestMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class TestMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int i;
        
        public TestMethodRequestBody() {
        }
        
        public TestMethodRequestBody(int i) {
            this.i = i;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMethodResponse", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.TestMethodResponseBody Body;
        
        public TestMethodResponse() {
        }
        
        public TestMethodResponse(MainWebsite.WebServiceReference.TestMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class TestMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestMethodResult;
        
        public TestMethodResponseBody() {
        }
        
        public TestMethodResponseBody(string TestMethodResult) {
            this.TestMethodResult = TestMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MainWebsite.WebServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MainWebsite.WebServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(MainWebsite.WebServiceReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(MainWebsite.WebServiceReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(MainWebsite.WebServiceReference.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string customer;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string username, string password, string customer) {
            this.username = username;
            this.password = password;
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(MainWebsite.WebServiceReference.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(string AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEventForTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEventForType", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddEventForTypeRequestBody Body;
        
        public AddEventForTypeRequest() {
        }
        
        public AddEventForTypeRequest(MainWebsite.WebServiceReference.AddEventForTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddEventForTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string action;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string customer;
        
        public AddEventForTypeRequestBody() {
        }
        
        public AddEventForTypeRequestBody(string type, string action, string description, string customer) {
            this.type = type;
            this.action = action;
            this.description = description;
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEventForTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEventForTypeResponse", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddEventForTypeResponseBody Body;
        
        public AddEventForTypeResponse() {
        }
        
        public AddEventForTypeResponse(MainWebsite.WebServiceReference.AddEventForTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddEventForTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEventForTypeResult;
        
        public AddEventForTypeResponseBody() {
        }
        
        public AddEventForTypeResponseBody(string AddEventForTypeResult) {
            this.AddEventForTypeResult = AddEventForTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCustomer", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddCustomerRequestBody Body;
        
        public AddCustomerRequest() {
        }
        
        public AddCustomerRequest(MainWebsite.WebServiceReference.AddCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customer;
        
        public AddCustomerRequestBody() {
        }
        
        public AddCustomerRequestBody(string customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCustomerResponse", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddCustomerResponseBody Body;
        
        public AddCustomerResponse() {
        }
        
        public AddCustomerResponse(MainWebsite.WebServiceReference.AddCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddCustomerResult;
        
        public AddCustomerResponseBody() {
        }
        
        public AddCustomerResponseBody(string AddCustomerResult) {
            this.AddCustomerResult = AddCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLog", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddLogRequestBody Body;
        
        public AddLogRequest() {
        }
        
        public AddLogRequest(MainWebsite.WebServiceReference.AddLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string action;
        
        public AddLogRequestBody() {
        }
        
        public AddLogRequestBody(string ID, System.DateTime timestamp, string action) {
            this.ID = ID;
            this.timestamp = timestamp;
            this.action = action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLogResponse", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddLogResponseBody Body;
        
        public AddLogResponse() {
        }
        
        public AddLogResponse(MainWebsite.WebServiceReference.AddLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddLogResult;
        
        public AddLogResponseBody() {
        }
        
        public AddLogResponseBody(string AddLogResult) {
            this.AddLogResult = AddLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddType", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddTypeRequestBody Body;
        
        public AddTypeRequest() {
        }
        
        public AddTypeRequest(MainWebsite.WebServiceReference.AddTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customer;
        
        public AddTypeRequestBody() {
        }
        
        public AddTypeRequestBody(string type, string customer) {
            this.type = type;
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTypeResponse", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddTypeResponseBody Body;
        
        public AddTypeResponse() {
        }
        
        public AddTypeResponse(MainWebsite.WebServiceReference.AddTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTypeResult;
        
        public AddTypeResponseBody() {
        }
        
        public AddTypeResponseBody(string AddTypeResult) {
            this.AddTypeResult = AddTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUnitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUnit", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddUnitRequestBody Body;
        
        public AddUnitRequest() {
        }
        
        public AddUnitRequest(MainWebsite.WebServiceReference.AddUnitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddUnitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UnitID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Room;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string customer;
        
        public AddUnitRequestBody() {
        }
        
        public AddUnitRequestBody(string UnitID, string Room, string type, string customer) {
            this.UnitID = UnitID;
            this.Room = Room;
            this.type = type;
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUnitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUnitResponse", Namespace="http://grandt.us:90/WebService/", Order=0)]
        public MainWebsite.WebServiceReference.AddUnitResponseBody Body;
        
        public AddUnitResponse() {
        }
        
        public AddUnitResponse(MainWebsite.WebServiceReference.AddUnitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grandt.us:90/WebService/")]
    public partial class AddUnitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddUnitResult;
        
        public AddUnitResponseBody() {
        }
        
        public AddUnitResponseBody(string AddUnitResult) {
            this.AddUnitResult = AddUnitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfaceSoapChannel : MainWebsite.WebServiceReference.InterfaceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceSoapClient : System.ServiceModel.ClientBase<MainWebsite.WebServiceReference.InterfaceSoap>, MainWebsite.WebServiceReference.InterfaceSoap {
        
        public InterfaceSoapClient() {
        }
        
        public InterfaceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int HelloAdd(int a, int b) {
            return base.Channel.HelloAdd(a, b);
        }
        
        public System.Threading.Tasks.Task<int> HelloAddAsync(int a, int b) {
            return base.Channel.HelloAddAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainWebsite.WebServiceReference.TestMethodResponse MainWebsite.WebServiceReference.InterfaceSoap.TestMethod(MainWebsite.WebServiceReference.TestMethodRequest request) {
            return base.Channel.TestMethod(request);
        }
        
        public string TestMethod(int i) {
            MainWebsite.WebServiceReference.TestMethodRequest inValue = new MainWebsite.WebServiceReference.TestMethodRequest();
            inValue.Body = new MainWebsite.WebServiceReference.TestMethodRequestBody();
            inValue.Body.i = i;
            MainWebsite.WebServiceReference.TestMethodResponse retVal = ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).TestMethod(inValue);
            return retVal.Body.TestMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.TestMethodResponse> MainWebsite.WebServiceReference.InterfaceSoap.TestMethodAsync(MainWebsite.WebServiceReference.TestMethodRequest request) {
            return base.Channel.TestMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainWebsite.WebServiceReference.TestMethodResponse> TestMethodAsync(int i) {
            MainWebsite.WebServiceReference.TestMethodRequest inValue = new MainWebsite.WebServiceReference.TestMethodRequest();
            inValue.Body = new MainWebsite.WebServiceReference.TestMethodRequestBody();
            inValue.Body.i = i;
            return ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).TestMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainWebsite.WebServiceReference.HelloWorldResponse MainWebsite.WebServiceReference.InterfaceSoap.HelloWorld(MainWebsite.WebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MainWebsite.WebServiceReference.HelloWorldRequest inValue = new MainWebsite.WebServiceReference.HelloWorldRequest();
            inValue.Body = new MainWebsite.WebServiceReference.HelloWorldRequestBody();
            MainWebsite.WebServiceReference.HelloWorldResponse retVal = ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.HelloWorldResponse> MainWebsite.WebServiceReference.InterfaceSoap.HelloWorldAsync(MainWebsite.WebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainWebsite.WebServiceReference.HelloWorldResponse> HelloWorldAsync() {
            MainWebsite.WebServiceReference.HelloWorldRequest inValue = new MainWebsite.WebServiceReference.HelloWorldRequest();
            inValue.Body = new MainWebsite.WebServiceReference.HelloWorldRequestBody();
            return ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainWebsite.WebServiceReference.LoginResponse MainWebsite.WebServiceReference.InterfaceSoap.Login(MainWebsite.WebServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password) {
            MainWebsite.WebServiceReference.LoginRequest inValue = new MainWebsite.WebServiceReference.LoginRequest();
            inValue.Body = new MainWebsite.WebServiceReference.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            MainWebsite.WebServiceReference.LoginResponse retVal = ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.LoginResponse> MainWebsite.WebServiceReference.InterfaceSoap.LoginAsync(MainWebsite.WebServiceReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainWebsite.WebServiceReference.LoginResponse> LoginAsync(string username, string password) {
            MainWebsite.WebServiceReference.LoginRequest inValue = new MainWebsite.WebServiceReference.LoginRequest();
            inValue.Body = new MainWebsite.WebServiceReference.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainWebsite.WebServiceReference.AddUserResponse MainWebsite.WebServiceReference.InterfaceSoap.AddUser(MainWebsite.WebServiceReference.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public string AddUser(string username, string password, string customer) {
            MainWebsite.WebServiceReference.AddUserRequest inValue = new MainWebsite.WebServiceReference.AddUserRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.customer = customer;
            MainWebsite.WebServiceReference.AddUserResponse retVal = ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddUserResponse> MainWebsite.WebServiceReference.InterfaceSoap.AddUserAsync(MainWebsite.WebServiceReference.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddUserResponse> AddUserAsync(string username, string password, string customer) {
            MainWebsite.WebServiceReference.AddUserRequest inValue = new MainWebsite.WebServiceReference.AddUserRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.customer = customer;
            return ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainWebsite.WebServiceReference.AddEventForTypeResponse MainWebsite.WebServiceReference.InterfaceSoap.AddEventForType(MainWebsite.WebServiceReference.AddEventForTypeRequest request) {
            return base.Channel.AddEventForType(request);
        }
        
        public string AddEventForType(string type, string action, string description, string customer) {
            MainWebsite.WebServiceReference.AddEventForTypeRequest inValue = new MainWebsite.WebServiceReference.AddEventForTypeRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddEventForTypeRequestBody();
            inValue.Body.type = type;
            inValue.Body.action = action;
            inValue.Body.description = description;
            inValue.Body.customer = customer;
            MainWebsite.WebServiceReference.AddEventForTypeResponse retVal = ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddEventForType(inValue);
            return retVal.Body.AddEventForTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddEventForTypeResponse> MainWebsite.WebServiceReference.InterfaceSoap.AddEventForTypeAsync(MainWebsite.WebServiceReference.AddEventForTypeRequest request) {
            return base.Channel.AddEventForTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddEventForTypeResponse> AddEventForTypeAsync(string type, string action, string description, string customer) {
            MainWebsite.WebServiceReference.AddEventForTypeRequest inValue = new MainWebsite.WebServiceReference.AddEventForTypeRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddEventForTypeRequestBody();
            inValue.Body.type = type;
            inValue.Body.action = action;
            inValue.Body.description = description;
            inValue.Body.customer = customer;
            return ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddEventForTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainWebsite.WebServiceReference.AddCustomerResponse MainWebsite.WebServiceReference.InterfaceSoap.AddCustomer(MainWebsite.WebServiceReference.AddCustomerRequest request) {
            return base.Channel.AddCustomer(request);
        }
        
        public string AddCustomer(string customer) {
            MainWebsite.WebServiceReference.AddCustomerRequest inValue = new MainWebsite.WebServiceReference.AddCustomerRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddCustomerRequestBody();
            inValue.Body.customer = customer;
            MainWebsite.WebServiceReference.AddCustomerResponse retVal = ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddCustomer(inValue);
            return retVal.Body.AddCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddCustomerResponse> MainWebsite.WebServiceReference.InterfaceSoap.AddCustomerAsync(MainWebsite.WebServiceReference.AddCustomerRequest request) {
            return base.Channel.AddCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddCustomerResponse> AddCustomerAsync(string customer) {
            MainWebsite.WebServiceReference.AddCustomerRequest inValue = new MainWebsite.WebServiceReference.AddCustomerRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddCustomerRequestBody();
            inValue.Body.customer = customer;
            return ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainWebsite.WebServiceReference.AddLogResponse MainWebsite.WebServiceReference.InterfaceSoap.AddLog(MainWebsite.WebServiceReference.AddLogRequest request) {
            return base.Channel.AddLog(request);
        }
        
        public string AddLog(string ID, System.DateTime timestamp, string action) {
            MainWebsite.WebServiceReference.AddLogRequest inValue = new MainWebsite.WebServiceReference.AddLogRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddLogRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.timestamp = timestamp;
            inValue.Body.action = action;
            MainWebsite.WebServiceReference.AddLogResponse retVal = ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddLog(inValue);
            return retVal.Body.AddLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddLogResponse> MainWebsite.WebServiceReference.InterfaceSoap.AddLogAsync(MainWebsite.WebServiceReference.AddLogRequest request) {
            return base.Channel.AddLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddLogResponse> AddLogAsync(string ID, System.DateTime timestamp, string action) {
            MainWebsite.WebServiceReference.AddLogRequest inValue = new MainWebsite.WebServiceReference.AddLogRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddLogRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.timestamp = timestamp;
            inValue.Body.action = action;
            return ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainWebsite.WebServiceReference.AddTypeResponse MainWebsite.WebServiceReference.InterfaceSoap.AddType(MainWebsite.WebServiceReference.AddTypeRequest request) {
            return base.Channel.AddType(request);
        }
        
        public string AddType(string type, string customer) {
            MainWebsite.WebServiceReference.AddTypeRequest inValue = new MainWebsite.WebServiceReference.AddTypeRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddTypeRequestBody();
            inValue.Body.type = type;
            inValue.Body.customer = customer;
            MainWebsite.WebServiceReference.AddTypeResponse retVal = ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddType(inValue);
            return retVal.Body.AddTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddTypeResponse> MainWebsite.WebServiceReference.InterfaceSoap.AddTypeAsync(MainWebsite.WebServiceReference.AddTypeRequest request) {
            return base.Channel.AddTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddTypeResponse> AddTypeAsync(string type, string customer) {
            MainWebsite.WebServiceReference.AddTypeRequest inValue = new MainWebsite.WebServiceReference.AddTypeRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddTypeRequestBody();
            inValue.Body.type = type;
            inValue.Body.customer = customer;
            return ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainWebsite.WebServiceReference.AddUnitResponse MainWebsite.WebServiceReference.InterfaceSoap.AddUnit(MainWebsite.WebServiceReference.AddUnitRequest request) {
            return base.Channel.AddUnit(request);
        }
        
        public string AddUnit(string UnitID, string Room, string type, string customer) {
            MainWebsite.WebServiceReference.AddUnitRequest inValue = new MainWebsite.WebServiceReference.AddUnitRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddUnitRequestBody();
            inValue.Body.UnitID = UnitID;
            inValue.Body.Room = Room;
            inValue.Body.type = type;
            inValue.Body.customer = customer;
            MainWebsite.WebServiceReference.AddUnitResponse retVal = ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddUnit(inValue);
            return retVal.Body.AddUnitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddUnitResponse> MainWebsite.WebServiceReference.InterfaceSoap.AddUnitAsync(MainWebsite.WebServiceReference.AddUnitRequest request) {
            return base.Channel.AddUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainWebsite.WebServiceReference.AddUnitResponse> AddUnitAsync(string UnitID, string Room, string type, string customer) {
            MainWebsite.WebServiceReference.AddUnitRequest inValue = new MainWebsite.WebServiceReference.AddUnitRequest();
            inValue.Body = new MainWebsite.WebServiceReference.AddUnitRequestBody();
            inValue.Body.UnitID = UnitID;
            inValue.Body.Room = Room;
            inValue.Body.type = type;
            inValue.Body.customer = customer;
            return ((MainWebsite.WebServiceReference.InterfaceSoap)(this)).AddUnitAsync(inValue);
        }
    }
}
