//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateDatabaseInfo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LundbeckModelContainer : DbContext
    {
        public LundbeckModelContainer()
            : base("name=LundbeckModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dim_Unit_L> Dim_Unit_LSet { get; set; }
        public virtual DbSet<Dim_Unit_Type_L> Dim_Unit_Type_LSet { get; set; }
        public virtual DbSet<Dim_Location_L> Dim_Location_LSet { get; set; }
        public virtual DbSet<Bridge_Unit_L> Bridge_Unit_LSet { get; set; }
        public virtual DbSet<Dim_Event_L> Dim_Event_LSet { get; set; }
        public virtual DbSet<Bridge_Event_L> Bridge_Event_LSet { get; set; }
        public virtual DbSet<Fact_Unit_Log_L> Fact_Unit_Log_LSet { get; set; }
        public virtual DbSet<Fact_Unit_Data_L> Fact_Unit_Data_LSet { get; set; }
    }
}
