//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateDatabaseInfo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainModelContainer1 : DbContext
    {
        public MainModelContainer1()
            : base("name=MainModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Main_Dim_Unit> Main_Dim_UnitSet { get; set; }
        public virtual DbSet<Main_Dim_Customer> Main_Dim_CustomerSet { get; set; }
        public virtual DbSet<Main_Bridge_Customer_Unit> Main_Bridge_Customer_UnitSet { get; set; }
        public virtual DbSet<Main_Fact_Logs> Main_Fact_LogsSet { get; set; }
        public virtual DbSet<Main_Users> Main_UsersSet { get; set; }
    }
}
