//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateDatabaseInfo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnitModelContainer : DbContext
    {
        public UnitModelContainer()
            : base("name=UnitModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dim_Unit> Dim_UnitSet { get; set; }
        public virtual DbSet<Dim_Unit_Type> Dim_Unit_TypeSet { get; set; }
        public virtual DbSet<Dim_Location> Dim_LocationSet { get; set; }
        public virtual DbSet<Bridge_Unit> Bridge_UnitSet { get; set; }
        public virtual DbSet<Dim_Event> Dim_EventSet { get; set; }
        public virtual DbSet<Bridge_Event> Bridge_EventSet { get; set; }
        public virtual DbSet<Fact_Unit_Log> Fact_Unit_LogSet { get; set; }
        public virtual DbSet<Fact_Unit_Data> Fact_Unit_DataSet { get; set; }
    }
}
