//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bridge_EventSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bridge_EventSet()
        {
            this.Fact_Unit_LogSet = new HashSet<Fact_Unit_LogSet>();
        }
    
        public int Id { get; set; }
        public int Dim_Unit_TypeId { get; set; }
        public int Dim_EventId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fact_Unit_LogSet> Fact_Unit_LogSet { get; set; }
        public virtual Dim_EventSet Dim_EventSet { get; set; }
        public virtual Dim_Unit_TypeSet Dim_Unit_TypeSet { get; set; }
    }
}
