//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bridge_Unit_LSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bridge_Unit_LSet()
        {
            this.Fact_Unit_Data_LSet = new HashSet<Fact_Unit_Data_LSet>();
            this.Fact_Unit_Log_LSet = new HashSet<Fact_Unit_Log_LSet>();
        }
    
        public int Id { get; set; }
        public int Dim_UnitId { get; set; }
        public int Dim_Unit_TypeId { get; set; }
        public int Dim_LocationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fact_Unit_Data_LSet> Fact_Unit_Data_LSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fact_Unit_Log_LSet> Fact_Unit_Log_LSet { get; set; }
        public virtual Dim_Location_LSet Dim_Location_LSet { get; set; }
        public virtual Dim_Unit_Type_LSet Dim_Unit_Type_LSet { get; set; }
        public virtual Dim_Unit_LSet Dim_Unit_LSet { get; set; }
    }
}
