//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegionHEntities : DbContext
    {
        public RegionHEntities()
            : base("name=RegionHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bridge_EventSet> Bridge_EventSet { get; set; }
        public virtual DbSet<Bridge_UnitSet> Bridge_UnitSet { get; set; }
        public virtual DbSet<Dim_EventSet> Dim_EventSet { get; set; }
        public virtual DbSet<Dim_LocationSet> Dim_LocationSet { get; set; }
        public virtual DbSet<Dim_Unit_TypeSet> Dim_Unit_TypeSet { get; set; }
        public virtual DbSet<Dim_UnitSet> Dim_UnitSet { get; set; }
        public virtual DbSet<Fact_Unit_DataSet> Fact_Unit_DataSet { get; set; }
        public virtual DbSet<Fact_Unit_LogSet> Fact_Unit_LogSet { get; set; }
    }
}
